### PR TITLE
Fix TS declaration file

### PR DESCRIPTION
**Pull request by jakawell**
Fix TypeScript declaration file, since it was not properly exporting for latest version of TS (3.x)

### CODE REVIEW

**Comment by jakawell** [comment]
I could not get this to import into TypeScript, and realized that the declaration didn't seem to be quite right. I know this change makes it work in my code, but if the original works and my change is unnecessary, please let me know how it should properly be imported. 
Thanks!

**Comment by BrunnerLivio** [comment]
No, just double checked, the typings are out of date. Yours seems to be fine, thanks a lot :)

**Comment by BrunnerLivio** [comment]
`pokemongo-game-master@2.1.0` has been release with your changes

**Comment by jakawell** [comment]
Awesome! Thanks!

**Pull request merged**
