### PR TITLE
castform

### PR DESCRIPTION
**Pull request by celandro**

### CODE REVIEW

**Comment by celandro** [comment]
@dandesousa can you please approve this or give me the power to merge myself? You merged someone elses PR in front of mine and caused issues...

**Comment by dandesousa** [comment]
I hadn't realized you didn't have permission to merge? I think @BrunnerLivio needs to add you. I'll approve this to unblock you. Shouldn't cause issues should it? It was just a new version add and update to latest on his end. Can't you just rebase / amend and leave latest in place?

**Comment by BrunnerLivio** [comment]
@celandro @dandesousa I have removed the merge restriction now. I think it causes more trouble than improvement.

**Comment by dandesousa** [comment]
Also note the latest version mismatch...

**Comment by BrunnerLivio** [comment]
@dandesousa You recommend remove and force push the latest commit (1ca4d13c98e7f24c491d22ebe474be59d8e4fee7)?

I would prefer if we could just revert it with a new commit using [`git revert`](https://git-scm.com/docs/git-revert)

**Comment by celandro** [comment]
replacing with new pr

**Pull request closed without merging**
