### PR TITLE
Update GAME_MASTER with timestamp 1542581210773

### PR DESCRIPTION
**Pull request by dominicbarnes**
This new version adds the move "Meteor Mash" and includes some other rebalancing and fixes.

### CODE REVIEW

**Comment by BrunnerLivio** [comment]
Are the test cases wrong, or was the new version script wrongly executed / wrong time on host machine?

**Comment by dominicbarnes** [comment]
@BrunnerLivio looks when adding files it puts the timestamp somewhere in the future

 - `1540779412719` = Monday, October 29, 2018 2:16:52.719 AM (#25)
 - `1540713609079` = Sunday, October 28, 2018 8:00:09.079 AM (this PR)

I ran this script days ago, and the timestamps still reflect the future. (I assume the numbers used are millisecond unix timestamps)

**Comment by dominicbarnes** [comment]
I just looked at `add-version.sh`, it looks like it uses `timestampMs` from the `GAME_MASTER` file, not the current time. I expected that property to reflect when the file was generated, but maybe it's an expiration instead?

In any case, I'm going to rebuild this PR with a new "latest" version, rather than try to fix this by hand.

**Comment by dominicbarnes** [comment]
@BrunnerLivio this PR should be ready to go now!

**Pull request merged**
