### PR TITLE
Add hydrocannon

### PR DESCRIPTION
**Pull request by celandro**
Still don't like us trying to version based off this weird Niantic versioning scheme.

yyyymmdd seems much easier but if there is a place for me to find out what the version number would be today I guess that would be ok too.

### CODE REVIEW

**Comment by BrunnerLivio** [comment]
Lets discuss this in #11. This seems to be a bigger issue

**Comment by dominicbarnes** [comment]
While the discussion in #11 is ongoing, can we go ahead and get this merged in?

**Comment by BrunnerLivio** [comment]
Do not see a problem with that. @dominicbarnes

**Comment by celandro** [comment]
Can we reduce number of approvers to 1 as well?

**Comment by BrunnerLivio** [comment]
@celandro done

**Pull request merged**
