### PR TITLE
Community day and contrib directory

### PR DESCRIPTION
**Pull request by celandro**
This has 2 commints

The first is my historical dump. I could potentially get more out of git history if need be.

The 20180812_pokemongo.json file is what I suggest be made for community days by hand. What I did was make a copy of the most recent json, delete all irrelevant data except the pokemon involved. Then added the possible movesets available during the community day.

The second is an update to the latest protos that includes LAST_RESORT

Let me know what you think.

### CODE REVIEW

**Comment by BrunnerLivio** [comment]
I do not like the folder name "pokebattler", because it is really specific to your application. Do you have other suggestions for the folder name like "community_days" or "legacy"? Does that make sense?


> The second is an update to the latest protos that includes LAST_RESORT

The second what ...?

**Comment by celandro** [comment]
Second commit.

I agree don't call it Pokebattler I just didn't know what to call them.
They are partially hand modified and need work to convert them to community
days. I'd also need to convert the file names to the ms format.

I'm swamped with other work right now though so thought id make.this
available if anyone else wants to finish the pr.

**Comment by dominicbarnes** [comment]
I'm trying to import a new file with "Last Resort" included. I don't necessarily need all the community day moves, so I'm wondering if this PR can be split into 2. (1: add community day files and 2: add latest with last resort)

I'm trying to open my own PR, but I keep getting dependency errors in maven:

> [ERROR] Failed to execute goal on project pokemongo-game-master: Could not resolve dependencies for project com.pokebattler:pokemongo-game-master:jar:2.30.1: Could not find artifact com.pokebattler:pogoprotos:jar:2.30.1 in pokemongo-dev-contrib-pogoprotos-java (https://packagecloud.io/pokemongo-dev-contrib/pogoprotos-java/maven2) -> [Help 1]

**Comment by celandro** [comment]
Added the readme

**Pull request merged**
