### PR TITLE
Add Exeggutor Alola. Will need another update soon

### PR DESCRIPTION
**Pull request by celandro**

### CODE REVIEW

**Comment by dominicbarnes** [comment]
@BrunnerLivio @celandro will this update fix the issue blocking #1?

**Comment by dominicbarnes** [comment]
I just ported the changes to `pom.xml` and re-ran the import script and it looks like that is, in fact, the issue. I'd like to see this merged and I'm more than happy to submit my own replacement for #1 if @dandesousa doesn't have the time.

**Comment by dandesousa** [comment]
Sorry this week has been hectic for me, I only just saw this and I hadn't had a chance to look. 

Bikeshed: Should the version should be 0.105.0 as it corresponds to the version forced where it was launched. Not sure how much we've been historically tracking it.

**Comment by dandesousa** [comment]
@dominicbarnes this should be inclusive of that GM file, shouldn't need that one if this merges.

**Comment by celandro** [comment]
It probably should. I always struggle with the version numbers

**Comment by dandesousa** [comment]
I tried to push to your branch but I don't have write on the repos to update the version number -- I put up a PR with 0.101.1 -> 0.105.0 so we can either merge that or you can cherry-pick the commit here or just update the version number -- just trying to save you the trouble.

https://github.com/pokemongo-dev-contrib/pokemongo-game-master/pull/4

**Comment by celandro** [comment]
Sorry u have to gotten to this. I've been too busy trying to make my
servers not crash

**Comment by celandro** [comment]
PS. It looks like furtiv updated the enums so we just need a new
pogoprotos-java release and everything will work

https://github.com/Furtif/POGOProtos

**Comment by Furtif** [comment]
yes pogoprotos is on for 105

**Comment by Furtif** [comment]
https://github.com/Furtif/POGOProtos/commit/09747417f8920d776e612d8cabd47ff6195febf8

**Comment by Furtif** [comment]
@dandesousa pt? br ?

**Comment by dandesousa** [comment]
pt -- born in US, parents are pt

**Comment by Furtif** [comment]
Está-se bem fixe :-)

**Pull request merged**
