### PR TITLE
New Gen 4 Mons and PvP Move Rebalance

### PR DESCRIPTION
**Pull request by celandro**
Ran the script after work.

### CODE REVIEW

**Comment by egw** [comment]
Hi. Thanks for doing this! I noticed an issue, though. Some of the pvp-related templates are blank, specifically BELUGA_POKEMON_WHITELIST and COMBAT_xxx, starting at line 7135.

Thanks again!

**Comment by celandro** [comment]
I need to release the latest pogoprotos-java and rerun. I will try and
remember to do that tonight

**Comment by dandesousa** [comment]
It looks like the initial commits didn't contain the adjustments to move energy / power. I pulled the latest proto and added the new version

**Comment by dandesousa** [comment]
Since I made the last change I'll let someone take a quick look and merge

**Pull request merged**
